name: Deploy master
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup SSL
        run: |
          pwd
          printf '%s\n' "${{ secrets.SERVER }}" > "server.crt"
          printf '%s\n' "${{ secrets.PRIVATE }}" > "server.key"
          ls
      - name: Docker Build
        run: |
          docker build --pull -t roberta -f Dockerfile
          docker tag roberta andreiliphd/roberta:latest
          docker push roberta andreiliphd/roberta:latest
      - name: Add SSH Key
        run: |
          mkdir -p "$HOME/.ssh"
          printf '%s\n' "${{ secrets.DOCKER_SSH_PRIVATE_KEY }}" > "$HOME/.ssh/id_rsa"
          chmod 600 "$HOME/.ssh/id_rsa"
          eval $(ssh-agent)
          ssh-add "$HOME/.ssh/id_rsa"
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
      - name: Run Docker Container
        run: |
          ssh root@${{ secrets.HOST }} "docker stop roberta" || true
          ssh root@${{ secrets.HOST }} "docker rm roberta" || true
          ssh root@${{ secrets.HOST }} "docker pull andreiliphd/roberta:latest" || true
          ssh root@${{ secrets.HOST }} "docker run -d --restart always --name roberta -p 443:443 andreiliphd/roberta:latest"